### PR TITLE
First draft for members to be able to view their own registered cards,

### PR DESCRIPTION
**Pull request by alex-wells**
change the activation state of them and give them friendly names.

Includes schema modification for rfid_tags table to add friendly_name column

Some awful fudges to get some of the id/name string lookups working for the state column - this needs resolving to everyone's satisfaction :P

WARNING: Inconsistency in some function naming scheme; I'll fix this at some point...

### CODE REVIEW

**Comment by geeksareforlife** [comment]
I know we didn't talk about this the other day, but if we are changing the DB, can we create an update file to run on the production server please?

The update files are in dev/Setup/Updates and are named after the version we are going to (so would be 0.3.8.php in this case - or maybe we should make this 0.4.0? - would it be better to branch off a 0.4.0 branch and merge this PR into there?)

**Comment by alex-wells** [comment]
@daniel1111 - it seems as though that's a windows-ism; I've locally changed the name of the file, and git hasn't noticed there's anything different. Unfortunately, windows doesn't care about filename case, which'll be why it worked initially.

@geeksareforlife - I can do that; are we just talking adding an `ALTER TABLE` script? As to what branch, whichever makes more sense :+1:

**Comment by geeksareforlife** [comment]
pretty much - you can look at the other scripts there and follow their general layout

As for the branch - I'd like us to get to a more professional release type thing, but for now, let's just say the next release is going to be 0.4.0

**Comment by alex-wells** [comment]
Should cover everything mentioned above...

**Comment by geeksareforlife** [comment]
Fixed isAuthorised and merged master back in

**Pull request merged**
