### PR TITLE
Enhancement.#67

### PR DESCRIPTION
**Pull request by jamesfowkes**
Think this is done now!

I accidentally pushed most of it to master anyway. I'm not even going to try fixing that because bad things will happen.

### CODE REVIEW

**Comment by dpslwk** [comment]
Never push to master!!!
I’ll see about fixing it

‘RepRap’ Matt

**Comment by jamesfowkes** [comment]
Yeah, I'm just setting up a .pre-push script to stop me in my tracks if I try that again.
http://dev.ghost.org/prevent-master-push/

**Comment by geeksareforlife** [comment]
Don't bother fixing it, it'll only end up messing up something.

Mistakes happen, we might as well remember them in the commit history!

**Comment by dpslwk** [comment]
to late its already done, only need a force push back to the correct commit

‘RepRap’ Matt

**Comment by jamesfowkes** [comment]
#neveragain

james@jamespc:~/Documents/Code/hms$ git push
Pushing to master is forbidden!
error: failed to push some refs to 'git@github.com:nottinghack/hms.git'

**Pull request merged**
