### PR TITLE
Added confirm dialog for approve member

### PR DESCRIPTION
**Pull request by jamesfowkes**

### CODE REVIEW

**Comment by geeksareforlife** [comment]
Where does this happen?  So I can test

**Comment by roberthunt** [comment]
You can approve members from:
- A link in the "actions" column at /members/listMembersWithStatus/4
- by viewing a member who has the status "Waiting for standing order payment"

**Comment by jamesfowkes** [comment]
Yeah, what Rob said.

**Comment by jamesfowkes** [comment]
Should see a JS driven dialog when you click approve.

**Comment by geeksareforlife** [comment]
Works perfectly

**Pull request merged**
